-- Aggregates every operator module under the canonical `reactivex/operators/*`
-- path so hosts that load this file directly (e.g., PZ file layout) get the
-- full operator set initialized.
require("reactivex/operators/filter")
require("reactivex/operators/distinct")
require("reactivex/operators/amb")
require("reactivex/operators/retry")
require("reactivex/operators/last")
require("reactivex/operators/merge")
require("reactivex/operators/skipWhile")
require("reactivex/operators/switch")
require("reactivex/operators/take")
require("reactivex/operators/skipLast")
require("reactivex/operators/window")
require("reactivex/operators/flatten")
require("reactivex/operators/sample")
require("reactivex/operators/defaultIfEmpty")
require("reactivex/operators/flatMap")
require("reactivex/operators/zip")
require("reactivex/operators/min")
require("reactivex/operators/flatMapLatest")
require("reactivex/operators/compact")
require("reactivex/operators/reject")
require("reactivex/operators/concat")
require("reactivex/operators/takeUntil")
require("reactivex/operators/first")
require("reactivex/operators/contains")
require("reactivex/operators/delay")
require("reactivex/operators/takeWhile")
require("reactivex/operators/with")
require("reactivex/operators/unwrap")
require("reactivex/operators/pack")
require("reactivex/operators/map")
require("reactivex/operators/startWith")
require("reactivex/operators/skip")
require("reactivex/operators/tap")
require("reactivex/operators/buffer")
require("reactivex/operators/average")
require("reactivex/operators/skipUntil")
require("reactivex/operators/partition")
require("reactivex/operators/takeLast")
require("reactivex/operators/find")
require("reactivex/operators/combineLatest")
require("reactivex/operators/sum")
require("reactivex/operators/unpack")
require("reactivex/operators/count")
require("reactivex/operators/debounce")
require("reactivex/operators/ignoreElements")
require("reactivex/operators/max")
require("reactivex/operators/reduce")
require("reactivex/operators/catch")
require("reactivex/operators/distinctUntilChanged")
require("reactivex/operators/all")
require("reactivex/operators/scan")
require("reactivex/operators/elementAt")
require("reactivex/operators/pluck")
require("reactivex/operators/publish")
require("reactivex/operators/refCount")
require("reactivex/operators/share")

-- Also register under the namespaced key so both `require("operators")` and
-- `require("reactivex/operators")` share the same loaded module.
local pkg = type(package) == "table" and package or { loaded = {} }
pkg.loaded = type(pkg.loaded) == "table" and pkg.loaded or {}
pkg.loaded["reactivex/operators"] = pkg.loaded["reactivex/operators"] or pkg.loaded["operators"] or true
